// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\_destructible_types_anim_lockers::main();
	maps\animated_models\fence_tarp_126x76_a_med_01::main();
	maps\animated_models\radar_spinning::main();
}
