// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\_destructible_types_anim_chicken::main();
	common_scripts\_destructible_types_anim_me_fanceil1_spin::main();
	maps\animated_models\seatown_canopy_1section_01_sway::main();
	maps\animated_models\seatown_canopy_1section_02_sway::main();
	maps\animated_models\seatown_canopy_3section_01_sway::main();
}
