// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_fullbody_ally_juggernaut");
	self setViewmodel("viewhands_juggernaut_ally");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_fullbody_ally_juggernaut");
	precacheModel("viewhands_juggernaut_ally");
}

enumerate_xmodels()
{
	models = [];
	models[models.size]="mp_fullbody_ally_juggernaut";
	models[models.size]="viewhands_juggernaut_ally";
	return models;
}
