// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_opforce_russian_air_sniper");
	self setViewmodel("viewhands_iw5_sniper_urban");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_opforce_russian_air_sniper");
	precacheModel("viewhands_iw5_sniper_urban");
}

enumerate_xmodels()
{
	models = [];
	models[models.size]="mp_body_opforce_russian_air_sniper";
	models[models.size]="viewhands_iw5_sniper_urban";
	return models;
}
