// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_opforce_russian_arctic_sniper");
	self setViewmodel("viewhands_iw5_sniper_snow");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_opforce_russian_arctic_sniper");
	precacheModel("viewhands_iw5_sniper_snow");
}

enumerate_xmodels()
{
	models = [];
	models[models.size]="mp_body_opforce_russian_arctic_sniper";
	models[models.size]="viewhands_iw5_sniper_snow";
	return models;
}
