// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_ally_delta_sniper");
	self setViewmodel("viewhands_delta_mp");
	self.voice = "delta";
}

precache()
{
	precacheModel("mp_body_ally_delta_sniper");
	precacheModel("viewhands_delta_mp");
}

enumerate_xmodels()
{
	models = [];
	models[models.size]="mp_body_ally_delta_sniper";
	models[models.size]="viewhands_delta_mp";
	return models;
}
