// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_ally_sas_sniper");
	self setViewmodel("viewhands_sas");
	self.voice = "british";
}

precache()
{
	precacheModel("mp_body_ally_sas_sniper");
	precacheModel("viewhands_sas");
}

enumerate_xmodels()
{
	models = [];
	models[models.size]="mp_body_ally_sas_sniper";
	models[models.size]="viewhands_sas";
	return models;
}
