// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_opforce_ghillie_africa_militia_sniper");
	self attach("head_ghillie_africa_militia_sniper", "", true);
	self.headModel = "head_ghillie_africa_militia_sniper";
	self setViewmodel("viewhands_african_militia");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_opforce_ghillie_africa_militia_sniper");
	precacheModel("head_ghillie_africa_militia_sniper");
	precacheModel("viewhands_african_militia");
}

enumerate_xmodels()
{
	models = [];
	models[models.size]="mp_body_opforce_ghillie_africa_militia_sniper";
	models[models.size]="head_ghillie_africa_militia_sniper";
	models[models.size]="viewhands_african_militia";
	return models;
}
