// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_opforce_russian_woodland_sniper");
	self setViewmodel("viewhands_iw5_sniper_rus_a");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_opforce_russian_woodland_sniper");
	precacheModel("viewhands_iw5_sniper_rus_a");
}

enumerate_xmodels()
{
	models = [];
	models[models.size]="mp_body_opforce_russian_woodland_sniper";
	models[models.size]="viewhands_iw5_sniper_rus_a";
	return models;
}
