// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_opforce_ghillie_urban_sniper");
	self attach("head_opforce_russian_urban_sniper", "", true);
	self.headModel = "head_opforce_russian_urban_sniper";
	self setViewmodel("viewhands_iw5_ghillie_urban");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_opforce_ghillie_urban_sniper");
	precacheModel("head_opforce_russian_urban_sniper");
	precacheModel("viewhands_iw5_ghillie_urban");
}

enumerate_xmodels()
{
	models = [];
	models[models.size]="mp_body_opforce_ghillie_urban_sniper";
	models[models.size]="head_opforce_russian_urban_sniper";
	models[models.size]="viewhands_iw5_ghillie_urban";
	return models;
}
