// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_opforce_africa_militia_sniper");
	self setViewmodel("viewhands_iw5_sniper_woodland");
	self.voice = "african";
}

precache()
{
	precacheModel("mp_body_opforce_africa_militia_sniper");
	precacheModel("viewhands_iw5_sniper_woodland");
}

enumerate_xmodels()
{
	models = [];
	models[models.size]="mp_body_opforce_africa_militia_sniper";
	models[models.size]="viewhands_iw5_sniper_woodland";
	return models;
}
